// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PenjualanUMKM.Context;

#nullable disable

namespace PenjualanUMKM.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PenjualanUMKM.Models.Antrian", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("idSales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noAntrian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Antrians");
                });

            modelBuilder.Entity("PenjualanUMKM.Models.LogUMKM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("judul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("keterangan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("noTiket")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogUMKMs");
                });

            modelBuilder.Entity("PenjualanUMKM.Models.Pelanggan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("namaPelanggan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pelanggans");
                });

            modelBuilder.Entity("PenjualanUMKM.Models.Penjualan", b =>
                {
                    b.Property<string>("noSales")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("idPelanggan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jenisPembayaran")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("totalHarga")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("noSales");

                    b.ToTable("Penjualans");
                });

            modelBuilder.Entity("PenjualanUMKM.Models.Produk", b =>
                {
                    b.Property<string>("kodeProduk")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("hargaProduk")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("namaProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("kodeProduk");

                    b.ToTable("Produks");
                });

            modelBuilder.Entity("PenjualanUMKM.Models.Transaksi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("idProduk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idSales")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transaksis");
                });
#pragma warning restore 612, 618
        }
    }
}
